### ISSUE TITLE
Geolocation of the buildings

### ISSUE THREAD

**Issue by NotBad4U** [kladier/miniprojet-android#2]
- [x] Integrate a google map view.
- [ ] Store buildings infos in firebase (u1 - u4).  `BEST EFFORT`
- [x] Add a search bar to find a building.
- [x] Display the marks on the map.

**Comment by NotBad4U** [comment]
We'll use [map-sdk](https://www.mapbox.com/android-docs/map-sdk/overview/) for openstreetmap.

**Comment by NotBad4U** [comment]
Integrate a google map view :heavy_check_mark:  with #8

**Comment by NotBad4U** [comment]
Depend on #11

**Comment by NotBad4U** [comment]
Add a search bar to find a building. :heavy_check_mark:  with #9 
Display the marks on the map. :heavy_check_mark:  with #9

**Comment by NotBad4U** [comment]
Now with #15 I'll try to finish this task.

**Comment by NotBad4U** [comment]
@AmauryCa  can you store this [infos ](https://github.com/kladier/miniprojet-android/blob/c69fb60fbe9f4aa35d7a398d0377473d4a123ae7/app/src/main/java/univ/pr/nj/keewitz/MapActivity.java#L269) in firebase and get them during the load of the activity  (maybe at the end of `onMapReady`).

**Comment by kladier** [comment]
done @AmauryCa ?

**Comment by AmauCgy** [comment]
Yes
