### ISSUE TITLE
Home menu

### ISSUE THREAD

**Issue by NotBad4U** [kladier/miniprojet-android#3]
- [x]  Add 3 buttons to go on other activities (ma fac, mes cours, configuration).
- [x] A list of card view and one card for each activity

**Comment by NotBad4U** [comment]
@kladier seem's to be done no ? 
_Maybe its a little ugly and we can just change the style of the button ?_

**Comment by kladier** [comment]
Done, un 4ème bouton va venir avec le QR code (temporaire, après y faudra cliquer sur mes cours et avoir 2 choix : EDT ou QR Code).
C'est à améliorer avec ce fameux "menu avec deux niveaux :
Ma fac : 1+4
Mes cours : 2+3
Confguration : 5+6"

**Comment by NotBad4U** [comment]
On peut tenter une vue de deuxième niveau en [tabs layout](https://www.androidhive.info/2015/09/android-material-design-working-with-tabs/).
Le truc c'est que c'est full `Fragment` donc moyen chaud.

**Comment by kladier** [comment]
Je pensais plus à un truc simple comme ça : https://i.stack.imgur.com/ke07F.png (mais avec seulement 2 levels)
Mais pas regardé si ya des trucs tout fait dans Android

**Comment by NotBad4U** [comment]
C'est pas tout à fait adapté à une navigation pour téléphone donc je doute qu'on trouve une librairie pour. Et refaire sois même c'est trop de charge de travail.

**Comment by NotBad4U** [comment]
Done :heavy_check_mark: in  #13 (still need a review)
