### ISSUE TITLE
Signal an anomaly

### ISSUE THREAD

**Issue by NotBad4U** [kladier/miniprojet-android#4]
- [x] take a photo.
- [x] select the level of criticality. 
- [ ] draw one rectangle on the photo.
- [x] add a send button that store the infos in firebase and jump to the geolocation activity.

**Comment by NotBad4U** [comment]
@AmauryCa, Do you think you'll implement the feature: `draw one rectangle on the photo.
` ?

**Comment by kladier** [comment]
pas de dessin et on close l'issue ?

**Comment by AmauCgy** [comment]
pas le time, on close
