### ISSUE TITLE
Display timetable

### ISSUE THREAD

**Issue by NotBad4U** [kladier/miniprojet-android#5]
- [x] Display the timetable of the  student in a iframe. 
- [x] Get from the setting the timetable to retrieve (M2DL by default)

**Comment by NotBad4U** [comment]
@kladier Have you done this part ? We have a requirement that has to work with all the timetable or just the one for M2DL ?

**Comment by kladier** [comment]
pour l'instant c'est en dur l'EDT des M2DL.
Ca va venir avec les settings

**Comment by kladier** [comment]
Pourquoi vouloir intégrer un client http ?

**Comment by NotBad4U** [comment]
Je pensais qu'il y en avait besoin mais non donc j'edit.

**Comment by NotBad4U** [comment]
Depend on #11
