### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by NotBad4U** [kladier/miniprojet-android#6]
- [x] Url of the timetable, training
- [x] Use the sensors to get the luminosity
- :no_entry:  Use the sensors to get sound level.
- [x] Our photos, names, master dl

**Comment by kladier** [comment]
Photo / name et logo du masterDL mis sur la home page
Les sensor lumière et son pas fait.
Pour le form nom de l'user / url EDT / nom de la formation c'est presque bon, ça attend d'être branché à firebase

**Comment by kladier** [comment]
Luminosité et son c'était pas là.
Sinon tout est ok sauf que quand on revient sur les Settings, ça affiche le choix par défaut M2DL au lieu du choix sauvegardé.
Je fixerais si j'ai le temps, en attendant je close
